### ISSUE TITLE
Converting Local Phone Number Based on User's Locale

### ISSUE THREAD

**Issue by Jayvd** [bottlepay/flutter_libphonenumber#11]
How do we achieve this. Let's say the phone number is `016123456` and the user's device is located in **Singapore** (**+65**). How do we convert it automatically using the library to `+6516123456`.

Any thoughts? Thank you

**Comment by Jawshua** [comment]
Hey @Jayvd,

You can pass a default region to the `parse` function. The input will then be treated as a local number for that region if there's no country code detected in the input.

**Comment by Jayvd** [comment]
@Jawshua Thanks for replying. If we don't know which country the user in currently in, how do we pass in the default region?

Sorry for bothering you with questions, Jawshua

**Comment by acoutts** [comment]
> @Jawshua Thanks for replying. If we don't know which country the user in currently in, how do we pass in the default region?
> 
> Sorry for bothering you with questions, Jawshua

You'll need to specify the country because many countries share the same phone code, so you can't derive it just from the phone number.

**Comment by Jayvd** [comment]
```
await FlutterLibphonenumber().init();
String locale = await CountryManager().deviceLocaleCountryCode;
await FlutterLibphonenumber().parse(recipientContact.flattenedPhone, region:  locale);
```

This is what I did, But I get an error

```
Unhandled Exception: PlatformException(InvalidNumber, Failed to parse phone number string '+7075551854'., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
```

Any thoughts ??  Thank you

**Comment by acoutts** [comment]
Does `locale` match a valid ISO region? `UK`, `US`, etc. It seems like locale might just return the language, like `en` or `es`.

**Comment by acoutts** [comment]
Closing due to inactivity.
